[package]
name = "RustBoids2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.6.0"
rand = "0.8.4"
benimator = "2.0.0-rc.1"
crossbeam = "0.7.3"
num_cpus = "1.0"
